### ISSUE TITLE
Error deploying to Vercel.

### ISSUE THREAD

**Issue by AjGaht** [cosmicjs/agency-template#24]
Error on Webpack and Fonts.

Build log :

[12:07:30.013] Running build in Washington, D.C., USA (East) – iad1
[12:07:30.125] Cloning github.com/AjGaht/v2_cosmic (Branch: main, Commit: fb529a7)
[12:07:30.463] Previous build cache not available
[12:07:30.497] Cloning completed: 372.318ms
[12:07:30.745] Running "vercel build"
[12:07:31.152] Vercel CLI 39.1.1
[12:07:31.511] Installing dependencies...
[12:07:31.559] bun install v1.1.36 (ededc168)
[12:07:33.395] Saved lockfile
[12:07:33.395] 
[12:07:33.395] + @types/node@20.17.6
[12:07:33.395] + @types/react@18.3.12
[12:07:33.396] + @types/react-dom@18.3.1
[12:07:33.396] + autoprefixer@10.4.20
[12:07:33.396] + eslint@8.57.1
[12:07:33.396] + eslint-config-next@14.0.3
[12:07:33.396] + postcss@8.4.47
[12:07:33.396] + prettier@3.3.3
[12:07:33.396] + prettier-plugin-tailwindcss@0.5.14
[12:07:33.396] + tailwindcss@3.4.14
[12:07:33.396] + typescript@5.6.3
[12:07:33.396] + @cosmicjs/sdk@1.2.0
[12:07:33.396] + @radix-ui/react-accordion@1.2.1
[12:07:33.396] + @radix-ui/react-dropdown-menu@2.1.2
[12:07:33.396] + @radix-ui/react-icons@1.3.1
[12:07:33.396] + @radix-ui/react-label@2.1.0
[12:07:33.396] + @radix-ui/react-navigation-menu@1.2.1
[12:07:33.396] + @radix-ui/react-select@2.1.2
[12:07:33.397] + @radix-ui/react-slot@1.1.0
[12:07:33.397] + @stripe/stripe-js@3.5.0
[12:07:33.397] + @types/bcryptjs@2.4.6
[12:07:33.397] + bcryptjs@2.4.3
[12:07:33.397] + class-variance-authority@0.7.0
[12:07:33.397] + clsx@2.1.1
[12:07:33.397] + lucide-react@0.456.0
[12:07:33.397] + next@14.0.0
[12:07:33.397] + next-themes@0.2.1
[12:07:33.397] + react@18.3.1
[12:07:33.397] + react-dom@18.3.1
[12:07:33.397] + react-markdown@9.0.1
[12:07:33.397] + react-medium-image-zoom@5.2.10
[12:07:33.397] + resend@4.0.1-alpha.0
[12:07:33.397] + stripe@14.25.0
[12:07:33.398] + tailwind-merge@2.5.4
[12:07:33.399] + tailwindcss-animate@1.0.7
[12:07:33.399] 
[12:07:33.399] 535 packages installed [1.86s]
[12:07:33.422] Detected Next.js version: 14.0.0
[12:07:33.426] Running "bun run build"
[12:07:33.431] $ next build
[12:07:34.152] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[12:07:34.152] This information is used to shape Next.js' roadmap and prioritize features.
[12:07:34.152] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[12:07:34.152] https://nextjs.org/telemetry
[12:07:34.152] 
[12:07:34.247]    ▲ Next.js 14.0.0
[12:07:34.248] 
[12:07:34.248]    Creating an optimized production build ...
[12:07:35.694] (node:133) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[12:07:35.695] (Use `node --trace-deprecation ...` to show where the warning was created)
[12:07:36.224] FetchError: request to https://fonts.gstatic.com/s/librefranklin/v18/jizDREVItHgc8qDIbSTKq4XkRiUS2zcZiVbJsNo.woff2 failed, reason: 
[12:07:36.224]     at ClientRequest.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
[12:07:36.224]     at ClientRequest.emit (node:events:518:28)
[12:07:36.224]     at ClientRequest.emit (node:domain:489:12)
[12:07:36.224]     at emitErrorEvent (node:_http_client:103:11)
[12:07:36.224]     at TLSSocket.socketErrorListener (node:_http_client:506:5)
[12:07:36.224]     at TLSSocket.emit (node:events:518:28)
[12:07:36.224]     at TLSSocket.emit (node:domain:489:12)
[12:07:36.224]     at emitErrorNT (node:internal/streams/destroy:170:8)
[12:07:36.224]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[12:07:36.224]     at processTicksAndRejections (node:internal/process/task_queues:90:21) {
[12:07:36.224]   type: 'system',
[12:07:36.224]   errno: 'ETIMEDOUT',
[12:07:36.224]   code: 'ETIMEDOUT'
[12:07:36.224] }
[12:07:36.225] FetchError: request to https://fonts.gstatic.com/s/librefranklin/v18/jizDREVItHgc8qDIbSTKq4XkRiUb2zcZiVbJsNo.woff2 failed, reason: 
[12:07:36.225]     at ClientRequest.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
[12:07:36.225]     at ClientRequest.emit (node:events:518:28)
[12:07:36.225]     at ClientRequest.emit (node:domain:489:12)
[12:07:36.225]     at emitErrorEvent (node:_http_client:103:11)
[12:07:36.225]     at TLSSocket.socketErrorListener (node:_http_client:506:5)
[12:07:36.226]     at TLSSocket.emit (node:events:518:28)
[12:07:36.226]     at TLSSocket.emit (node:domain:489:12)
[12:07:36.226]     at emitErrorNT (node:internal/streams/destroy:170:8)
[12:07:36.226]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[12:07:36.226]     at processTicksAndRejections (node:internal/process/task_queues:90:21) {
[12:07:36.226]   type: 'system',
[12:07:36.226]   errno: 'ETIMEDOUT',
[12:07:36.226]   code: 'ETIMEDOUT'
[12:07:36.226] }
[12:07:36.226] FetchError: request to https://fonts.gstatic.com/s/librefranklin/v18/jizDREVItHgc8qDIbSTKq4XkRiUQ2zcZiVbJsNo.woff2 failed, reason: 
[12:07:36.226]     at ClientRequest.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
[12:07:36.226]     at ClientRequest.emit (node:events:518:28)
[12:07:36.227]     at ClientRequest.emit (node:domain:489:12)
[12:07:36.227]     at emitErrorEvent (node:_http_client:103:11)
[12:07:36.227]     at TLSSocket.socketErrorListener (node:_http_client:506:5)
[12:07:36.227]     at TLSSocket.emit (node:events:518:28)
[12:07:36.227]     at TLSSocket.emit (node:domain:489:12)
[12:07:36.227]     at emitErrorNT (node:internal/streams/destroy:170:8)
[12:07:36.227]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[12:07:36.227]     at processTicksAndRejections (node:internal/process/task_queues:90:21) {
[12:07:36.227]   type: 'system',
[12:07:36.228]   errno: 'ETIMEDOUT',
[12:07:36.228]   code: 'ETIMEDOUT'
[12:07:36.228] }
[12:07:36.228] FetchError: request to https://fonts.gstatic.com/s/librefranklin/v18/jizDREVItHgc8qDIbSTKq4XkRiUR2zcZiVbJsNo.woff2 failed, reason: 
[12:07:36.228]     at ClientRequest.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
[12:07:36.228]     at ClientRequest.emit (node:events:518:28)
[12:07:36.228]     at ClientRequest.emit (node:domain:489:12)
[12:07:36.228]     at emitErrorEvent (node:_http_client:103:11)
[12:07:36.228]     at TLSSocket.socketErrorListener (node:_http_client:506:5)
[12:07:36.228]     at TLSSocket.emit (node:events:518:28)
[12:07:36.228]     at TLSSocket.emit (node:domain:489:12)
[12:07:36.228]     at emitErrorNT (node:internal/streams/destroy:170:8)
[12:07:36.228]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[12:07:36.228]     at processTicksAndRejections (node:internal/process/task_queues:90:21) {
[12:07:36.228]   type: 'system',
[12:07:36.228]   errno: 'ETIMEDOUT',
[12:07:36.228]   code: 'ETIMEDOUT'
[12:07:36.228] }
[12:07:36.229] FetchError: request to https://fonts.gstatic.com/s/librefranklin/v18/jizDREVItHgc8qDIbSTKq4XkRiUf2zcZiVbJ.woff2 failed, reason: 
[12:07:36.229]     at ClientRequest.<anonymous> (/vercel/path0/node_modules/next/dist/compiled/node-fetch/index.js:1:65756)
[12:07:36.229]     at ClientRequest.emit (node:events:518:28)
[12:07:36.229]     at ClientRequest.emit (node:domain:489:12)
[12:07:36.229]     at emitErrorEvent (node:_http_client:103:11)
[12:07:36.229]     at TLSSocket.socketErrorListener (node:_http_client:506:5)
[12:07:36.229]     at TLSSocket.emit (node:events:518:28)
[12:07:36.229]     at TLSSocket.emit (node:domain:489:12)
[12:07:36.229]     at emitErrorNT (node:internal/streams/destroy:170:8)
[12:07:36.229]     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
[12:07:36.229]     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
[12:07:36.229]   type: 'system',
[12:07:36.229]   errno: 'ETIMEDOUT',
[12:07:36.229]   code: 'ETIMEDOUT'
[12:07:36.229] }
[12:07:43.135] Failed to compile.
[12:07:43.135] 
[12:07:43.135] app/layout.tsx
[12:07:43.135] `next/font` error:
[12:07:43.135] Failed to fetch `Libre Franklin` from Google Fonts.
[12:07:43.135] 
[12:07:43.135] 
[12:07:43.135] > Build failed because of webpack errors
[12:07:43.166] error: script "build" exited with code 1
[12:07:43.174] Error: Command "bun run build" exited with 1
[12:07:43.968]

**Comment by tonyspiro** [comment]
Thank you for the report. Seems like an issue with fetching fonts and is not an issue with the template or Cosmic. Try to deploy again and it may be resolved. Closing this issue for now.

**Comment by AjGaht** [comment]
Kindly support :

Error: Missing API key. Pass it to the constructor `new Resend("re_123")`
    at new S (/vercel/path0/.next/server/chunks/835.js:9:41083)
    at 56057 (/vercel/path0/.next/server/chunks/508.js:1:3103)
    at __webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
    at 56957 (/vercel/path0/.next/server/app/forgot-password/page.js:1:4494)
    at Function.__webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:161)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async collectGenerateParams (/vercel/path0/node_modules/next/dist/build/utils.js:883:17)
> Build error occurred
Error: Failed to collect page data for /forgot-password
    at /vercel/path0/node_modules/next/dist/build/utils.js:1211:15
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {
  type: 'Error'
}
error: script "build" exited with code 1
Error: Command "bun run build" exited with 1

**Comment by AjGaht** [comment]
Working now!
Thanks @tonyspiro
